name: beditor
channels:
  - conda-forge
  - biocore
  - bioconda 
dependencies:
  - biopython=1.71
  - numpy=1.13.1
  - python=3.6.5
  - setuptools=39.2.0
  - pyyaml
  - datacache=1.1.4
  - pip:
    - matplotlib==2.2.2
    - pysam==0.14.1
    - requests==2.19.1
    - scipy==1.1.0
    - tqdm==4.23.4
    - seaborn==0.8.1
    - pandas==0.23.3
    - git+https://github.com/rraadd88/pyensembl